language:
  - cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-5.0
            - libstdc++6
script:
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.4 1000
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.4 1000
  - sudo update-alternatives --config clang
  - sudo update-alternatives --config clang++
  - cd src
  - find /usr -type f -name "LLVMgold.so"
  - make clean
  - make 

