language:
  - cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-5.0-dev
script:
  - which clang++
  - which clang
  - cd src
  - sudo ln -s /usr/lib/llvm-5.0/lib/LLVMgold.so /usr/local/clang-5.0.0/lib/LLVMgold.so
  - make clean
  - make 

