language:
  - cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang

script:
  - cd src
  - locate LLVMgold.so
  - ls /usr/lib/clang*/lib/LLVMgold.so
  - make clean
  - make 

