language:
  - cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - llvm-dev

script:
  - cd src
  - find /usr -type f -name "LLVMgold.so"
  - make clean
  - make 

